### ISSUE TITLE
[FEATURE] BottomSheet 검토

### ISSUE THREAD

**Issue by ww8007** [pickly-team/pickly-frontend#22]
##안건

현재 BottomSheet를 라이브러리 사용하지 않고 직접 개발을 하려고 하던 중 개발 비용이 너무 큰 것 같은 느낌...
구현 중 모바일 버전은 잘 커버가 되지만 현재 데스크탑 버전에서의 처리가 문제

> addEventListener의 방식에서 마우스 이벤트는 touchmove와 다른게 가장 골칫거리 🫠

```tsx
    sheet.current?.addEventListener('touchstart', handleTouchStart);
    sheet.current?.addEventListener('touchmove', handleTouchMove);
    sheet.current?.addEventListener('touchend', handleTouchEnd);
```

- [ ] 라이브러리 사용
- [ ] 이 악물고 개발...?

**Comment by ww8007** [comment]
참고 레퍼런스

https://blog.mathpresso.com/bottom-sheet-for-web-55ed6cc78c00

**Comment by aeong98** [comment]
이거 가장 문제가 되는게 mouse 이벤트 핸들러랑, touch 이벤트 핸들러 처리가 다른게 문제가 되는걸까용??
동현님이 올려주신 레퍼런스 보니깐 x,y 값만 꺼내오면 내부 로직은 동일하게 가져갈 수 있을것같긴한데,, 저는 아래와 같이 만들기는 했었습니답 .. 근데 내부 로직조차 달라져야 한다면 동현님 말씀대로 오히려 개발 비용이 너무 심하게 들어가는 느낌이라 라이브러리 사용해도 될것같긴해요 

- MouseEvent.clientX : https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/clientX
- Touch.clientX : https://developer.mozilla.org/en-US/docs/Web/API/Touch/clientX

```tsx
    <SlideWrapper
      ref={wrapperRef}
      onMouseDown={(event) => {
        updateStartPositionX(event.clientX);
      }}
      onTouchStart={(event) => {
        updateStartPositionX(event.touches[0].clientX);
      }}
      onMouseMove={(event) => {
        updateMovedPositionX(event.clientX);
      }}
      onTouchMove={(event) => {
        updateMovedPositionX(event.touches[0].clientX);
      }}
      onMouseUp={moveToSlideDirection}
      onTouchEnd={moveToSlideDirection}
      {...restProps}
    >
```

**Comment by ww8007** [comment]
요거 이런 방식으로 구현했는데 너무 복잡해져서 😢
좀 간단하게 해볼 수 있는 방법 찾아볼게요 
내부 로직 자체도 innerHeight가 다르게 동작해서 저번주에 하다가 집어 던졌습니다 ㅎㅎ...
추후에 코드 올려볼게요

**Comment by aeong98** [comment]
근데 저희 다른  기능 개발할것도 많으니,,동현님 너무 힘드시면 라이브러리도 저는 좋습니당 키키

**Comment by ww8007** [comment]
일단 요번 주말까지 해보고 결정하겠습니다 😵‍💫

**Comment by ww8007** [comment]
일단 MVP 버전 까지는 라이브러리를 사용 하도록 하고
추후에 직접 개발한 라이브러리로 교체하는 식으로

## Reason

- [ ] 빠르게 올려야 하는 개발 비용에 비해서 공수가 큼
- [ ] pc 마우스 이벤트에 대한 검수가 미흡
