### ISSUE TITLE
[STYLE] 모든 SVG 아이콘 추가

### ISSUE THREAD

**Issue by ww8007** [pickly-team/pickly-frontend#39]
#21 

- [x] 피그마에 있는 모든 SVG 파일
- [x] SVG 네이밍에 대한 FIX

## 변경사항

- 23.03.20 UI 변경에 따른 아이콘 수정

- [x] 변경 사항 추가

**Comment by litsynp** [comment]
![image](https://user-images.githubusercontent.com/42485462/224734824-3041553d-1f9c-487b-99df-886620155173.png)

누락입니다
